project:
  type: website
  output-dir: "docs"

website:
  title: "Amy Mwikali Mwanga"
  navbar:
    left: 
      - text: "Home"
        file:  index.qmd
      - text: "Portfolio"
        file:  portfolio.qmd
      - text: "CV"
        file:  cv.qmd
    right:
      - icon: github
        href: https://github.com/amymwix
      - icon: Linkedin
        href: www.linkedin.com/in/amy-mwanga-870218149
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

